name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker_ubuntu:${GITHUB_SHA}

    - name: login to docker hub
      id: docker-hub
      env:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_PASSWORD}}
      run:
        docker login -u $username -p $password

    - name: push the docker image
      id: push-docker-image
      env:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_PASSWORD}}
      run: docker push ${{secrets.DOCKERHUB_USERNAME}}/docker_ubuntu:${GITHUB_SHA}
